### ISSUE TITLE
Inconsistent spira reporting

### ISSUE THREAD

**Issue by ros-certi** [Inflectra/cypress-sample#1]
I've been trying to setup this integration for a while now, using a simple demo project. While the cypress test automation works without a hitch, updating correlating Spira tests with the automation's result hasn't been working consistently. I've doublechecked test-related IDs as well as user / API key and user permissions and they all seem to be in place. What's more, Spira's own event viewer shows no logs for some of the attempts I've made. Any idea of what might be wrong? I've also noticed this extension hasn't been updated in a while - is it still supported?

**Comment by simonhbor** [comment]
Can you please contact our support team at support@inflectra.com and they will be able to help you with this.
